name: Build and Deploy

on:
  push:
    branches:
      - server-dev

permissions:
  contents: write

jobs:
  build:
    name: Build the Project
    runs-on: windows-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code 🛎️
        uses: actions/checkout@v4

      # Step 2: Install dependencies and build the project
      - name: Install Dependencies and Build 🔧
        run: |
          cd frontend
          npm ci --force
          npm run build

      # Step 3: Upload build folder as an artifact
      - name: Upload Build Artifacts 🔺
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: frontend/build

  deploy:
    name: Deploy to GitHub Pages
    needs: [build] # Ensures the build job completes before starting the deploy job
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code 🛎️
        uses: actions/checkout@v4

      # Step 2: Download the build artifacts
      - name: Download Build Artifacts 🔻
        uses: actions/download-artifact@v4
        with:
          name: site

      # Step 3: Deploy the site to GitHub Pages
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: 'site' # This should match the artifact name used in the build job
