name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ "server-dev" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: github-pages  # Specify environment here
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
      
    - name: Install dependencies
      run: |
        cd frontend
        npm install --legacy-peer-deps

    - name: Build project
      run: |
        cd frontend
        npm run build

    - name: Verify build output
      run: |
        ls -l frontend/build  # Verify the build directory

    - name: Setup Pages
      uses: actions/configure-pages@v5
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './frontend/build'  # Point to build folder
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4